# -*- coding: utf-8 -*-
"""La marche vers h8 (Nikolaï Grigoriev, 1930) — le roi gagnant fuit dans le mauvais coin.

Position exacte lue sur le diagramme de l'article de Noam Elkies (« Endgame
Explorations 9 : Grigoriev », American Chess Journal), solution commentée à
l'appui ; étude parue en 1930 et reprise dans « 1234 Modern End-Game Studies ».
Les 35 demi-coups de la ligne principale passent la tablebase un à un, et les
trois pièges (1.b4?, 1.Kb8?, 2.Ka7? pat) sont eux aussi des verdicts d'oracle.
"""


def c(fr, en):
    return {"fr": fr, "en": en}


COURSE = {
    "id": "eg-grigoriev-h8",
    "name": "Grigoriev's March to h8 (1930)",
    "side": "white",
    "kind": "endgame",
    "family": "practical",
    "level": "advanced",
    "rootFEN": "K7/8/1k6/1p6/8/2P5/1P6/8 w - - 0 1",
    "summary": c(
        "Grigoriev, 1930 : deux pions contre un, tout le monde au coin dame — et le SEUL chemin du gain passe par h8, à l'autre bout du monde. Seize coups de roi aller-retour pour voler une opposition. La plus belle démonstration jamais composée de ce qu'« aller ailleurs » veut dire.",
        "Grigoriev, 1930: two pawns against one, everyone in the queenside corner — and the ONLY winning path goes through h8, at the far end of the world. Sixteen king moves there and back to steal an opposition. The finest demonstration ever composed of what “going the other way” means.",
    ),
    "lines": [
        {
            "chapter": {"id": "main", "title": c("Le grand détour", "The grand detour")},
            "moves": [
                {"san": "b3",
                 "comment": c("Le seul premier coup : préparer c4 sans rien concéder. La poussée miroir 1.b4? laisse la nulle (voir le chapitre), et sortir le roi d'abord aussi.",
                              "The only first move: preparing c4 while conceding nothing. The mirror push 1.b4? lets the draw in (see that chapter), and so does moving the king first."),
                 "critical": True},
                {"san": "Ka5",
                 "comment": c("La meilleure défense : surveiller b4 et menacer …b4 soi-même. Le roi blanc semble n'avoir que des cases piégées…",
                              "The best defence: watching b4 while threatening …b4 himself. The white king seems to have nothing but poisoned squares…")},
                {"san": "Kb8",
                 "comment": c("…sauf une. 2.b4+? Ka6! annule, et le naturel 2.Ka7? ou 2.Kb7? se jette dans un PAT superbe (chapitre dédié). Le roi prend la seule sortie propre : la huitième rangée.",
                              "…except one. 2.b4+? Ka6! draws, and the natural 2.Ka7? or 2.Kb7? walks into a gorgeous STALEMATE (its own chapter). The king takes the only clean exit: the eighth rank."),
                 "critical": True},
                {"san": "b4"},
                {"san": "c4",
                 "comment": c("L'échange est fait : le pion c est passé, mais le roi noir tient l'opposition de couloir — b6 contre b8 — et compte escorter …Kc5-b4 dès que le roi blanc s'approche.",
                              "The trade is done: the c-pawn is passed, but the black king holds the corridor opposition — b6 against b8 — planning …Kc5-b4 the moment the white king comes near.")},
                {"san": "Kb6"},
                {"san": "Kc8"},
                {"san": "Kc6",
                 "comment": c("Le miroir : à chaque pas du roi blanc le long de la huitième, le roi noir répond en face le long de la sixième, sans jamais lâcher le pion c des yeux.",
                              "The mirror: each white step along the eighth rank is answered directly opposite along the sixth, the c-pawn never out of sight.")},
                {"san": "Kd8"},
                "Kd6",
                {"san": "Ke8"},
                "Ke6",
                {"san": "Kf8"},
                "Kf6",
                {"san": "Kg8"},
                "Kg6",
                {"san": "Kh8",
                 "comment": c("Le coup inouï de l'étude : le roi gagnant s'enferme dans le coin le plus perdu de l'échiquier. Mais suivez le miroir : 9…Kh6?? le briserait — c5! et le pion file (chapitre « Le miroir cassé »). Le roi noir doit rester colonne f.",
                              "The study's outrageous move: the winning king locks himself into the most godforsaken corner of the board. But watch the mirror: 9…Kh6?? would break it — c5! and the pawn runs (see “The broken mirror”). The black king must stay on the f-file."),
                 "critical": True},
                {"san": "Kf6",
                 "comment": c("Forcé, à distance de garde de c5. Et voilà le vol commis : les rois sont désormais h8-f6 — l'ancienne opposition directe a disparu dans le coin.",
                              "Forced, keeping guard over c5. And the theft is done: the kings now stand h8-f6 — the old direct opposition has vanished into the corner.")},
                {"san": "Kh7",
                 "comment": c("La redescente commence : rangée par rangée, le roi blanc plaque son homologue contre le duo h/f.",
                              "The descent begins: rank by rank, the white king pins his counterpart to the h/f duet.")},
                "Kf7",
                {"san": "Kh6"},
                "Kf6",
                {"san": "Kh5"},
                "Kf5",
                {"san": "Kh4"},
                {"san": "Kf4"},
                {"san": "Kh3",
                 "comment": c("L'avant-dernier échelon, et le plus fin : 14…Kf3? perdrait le contact avec c5 — c5! décide. Le roi noir doit remonter, et céder enfin la troisième rangée.",
                              "The next-to-last rung, and the finest: 14…Kf3? would lose touch with c5 — c5! decides. The black king must climb back, finally conceding the third rank."),
                 "critical": True},
                {"san": "Kf5"},
                {"san": "Kg3",
                 "comment": c("Regardez ce qui a changé : g3 contre f5 — c'est le roi BLANC qui a l'opposition latérale à présent. Le retour vers l'ouest sera une marche triomphale.",
                              "Look what has changed: g3 against f5 — it is the WHITE king who owns the lateral opposition now. The march back west will be a victory parade."),
                 "critical": True},
                {"san": "Kg5"},
                {"san": "Kf3"},
                "Kf5",
                {"san": "Ke3"},
                "Ke5",
                {"san": "Kd3",
                 "comment": c("Et le miroir meurt de sa belle mort : 18…Kd5 est interdit par le pion c4 ! Suivent Kd4, c5 et Kc4 — le pion est escorté. Trente-cinq demi-coups, un aller-retour jusqu'à h8, pour gagner UN temps : celui-ci.",
                              "And the mirror dies its beautiful death: 18…Kd5 is forbidden by the c4-pawn! Next come Kd4, c5 and Kc4 — the pawn is escorted home. Thirty-five half-moves, a round trip to h8, to win ONE tempo: this one."),
                 "critical": True},
            ],
        },
        {
            "chapter": {"id": "wrong-push", "title": c("La poussée miroir", "The mirror push")},
            "moves": [
                {"san": "b4", "role": "trap",
                 "comment": c("Un pion passé tout de suite — quoi de plus naturel ? Mais ce pion-là se juge à ce qu'il enferme :",
                              "A passed pawn at once — what could be more natural? But this pawn is judged by what it locks in:"),
                 "critical": True},
                {"san": "Ka6",
                 "comment": c("…son propre roi. Plus de b3-c4 pour ouvrir une route, plus de sortie par a7/b7 sous l'œil du roi noir : la navette a6-b6 tient la maison pour toujours. Verdict de la tablebase : nulle — le temps de préparation 1.b3! n'était pas un luxe.",
                              "…his own king. No more b3-c4 to open a road, no exit via a7/b7 under the black king's eye: the a6-b6 shuttle keeps house forever. Tablebase verdict: draw — the preparatory 1.b3! was no luxury.")},
            ],
        },
        {
            "chapter": {"id": "king-first", "title": c("Le roi part sans préparer", "The king leaves unprepared")},
            "moves": [
                {"san": "Kb8", "role": "trap",
                 "comment": c("Sortir d'abord, pousser ensuite ? L'ordre des coups est toute l'étude :",
                              "Step out first, push later? Move order is the whole study:"),
                 "critical": True},
                {"san": "b4",
                 "comment": c("La liquidation force la nulle — il ne restera pas de quoi gagner. Et attention au pire :",
                              "The liquidation forces the draw — nothing to win will remain. And beware of worse:")},
                {"san": "c4", "role": "trap",
                 "comment": c("Refuser l'échange PERD : le pion b file en b3-b2-b1 pendant que les pions blancs regardent. Il fallait 2.cxb4 — nulle sèche, les pions b doublés ne gagnent pas ici.",
                              "Declining the trade LOSES: the b-pawn runs b3-b2-b1 while the white pawns watch. 2.cxb4 was forced — a dead draw, the doubled b-pawns win nothing here."),
                 "critical": True},
                {"san": "b3",
                 "comment": c("Imparable. L'étude contenait donc les trois verdicts : un gain (b3!), des nulles, et même une défaite pour le camp « gagnant ».",
                              "Unstoppable. So the study held all three verdicts: one win (b3!), draws, and even a loss for the “winning” side.")},
            ],
        },
        {
            "chapter": {"id": "stalemate", "title": c("Le pat du coin", "The corner stalemate")},
            "moves": [
                "b3", "Ka5",
                {"san": "Ka7", "role": "trap",
                 "comment": c("La sortie « normale » — et le joyau caché de l'étude :",
                              "The “normal” exit — and the study's hidden jewel:"),
                 "critical": True},
                {"san": "b4"},
                {"san": "c4",
                 "comment": c("Regardez le roi noir : a4 et b5 pris par les pions, a6 et b6 par le roi — PAT. La même noyade guette 2.Kb7?. Seul 2.Kb8!, une rangée plus haut, laissait respirer a6 et b6 : voilà pourquoi le grand détour commence par le coin exact.",
                              "Look at the black king: a4 and b5 taken by the pawns, a6 and b6 by the king — STALEMATE. The same drowning awaits 2.Kb7?. Only 2.Kb8!, one rank higher, leaves a6 and b6 breathing: that is why the grand detour starts from the exact corner.")},
            ],
        },
        {
            "chapter": {"id": "broken-mirror", "title": c("Le miroir cassé", "The broken mirror")},
            "moves": [
                "b3", "Ka5", "Kb8", "b4", "c4", "Kb6", "Kc8", "Kc6", "Kd8", "Kd6",
                "Ke8", "Ke6", "Kf8", "Kf6", "Kg8", "Kg6", "Kh8",
                {"san": "Kh6",
                 "comment": c("Suivre jusqu'au bout du monde — le réflexe du miroir. Mais en h6, le roi noir ne voit plus c5 :",
                              "Following to the end of the world — the mirror reflex. But from h6 the black king no longer covers c5:")},
                {"san": "c5",
                 "comment": c("…et le pion démarre : c6, c7, c8=D, trois temps que le roi noir, coincé côté h, ne rattrapera jamais. Voilà pourquoi 9.Kh8! était sans risque : le duel ne se jouait pas entre rois, mais entre le roi noir et CETTE poussée.",
                              "…and the pawn is off: c6, c7, c8=Q, three tempi the black king, stuck on the h-side, will never claw back. That is why 9.Kh8! was riskless: the duel was never king against king, but the black king against THIS push."),
                 "critical": True},
            ],
        },
    ],
}
