# -*- coding: utf-8 -*-
"""Le pion qui passe outre (Leonid Kubbel, 1927) — ne prends pas : dépasse.

FEN et coup-clé (1.a6 !) sourcés ARVES (« instructive studies », Kubbel 1927,
gain blanc) ; toutes les lignes du cours sont dérivées de la tablebase, qui
confirme la finesse de l'étude : 1.a6 est l'UNIQUE gain, la prise naturelle
1.axb6? n'est que nulle, et les six coups de roi PERDENT tous contre le pion e.
"""


def c(fr, en):
    return {"fr": fr, "en": en}


COURSE = {
    "id": "eg-kubbel-1927",
    "name": "Kubbel's Passing Pawn (1927)",
    "side": "white",
    "kind": "endgame",
    "family": "practical",
    "level": "advanced",
    "rootFEN": "8/8/1p1K4/Pp6/2k1p3/8/1P6/8 w - - 0 1",
    "summary": c(
        "Kubbel, 1927 : cinq pions, deux rois, et une seule question — prendre en b6, ou passer outre ? La prise, réflexe de toute une vie, n'est que nulle ; les coups de roi perdent ; seul a5-a6 !! gagne, parce que la dame née en a8 verra des diagonales que sa jumelle de b8 n'aura jamais. Une étude sur la case de naissance des dames.",
        "Kubbel, 1927: five pawns, two kings, and a single question — capture on b6, or pass it by? The capture, a lifetime's reflex, only draws; the king moves lose; a5-a6!! alone wins, because a queen born on a8 will see diagonals her twin born on b8 never gets. A study about where queens are born.",
    ),
    "lines": [
        {
            "chapter": {"id": "main", "title": c("Passer outre", "Passing by")},
            "moves": [
                {"san": "a6",
                 "comment": c("Ni la prise (axb6? nulle — voir le piège), ni un coup de roi (les six perdent : le pion e file). Le pion DÉPASSE b6 : les pions noirs ne prennent qu'en descendant, a6 est donc intouchable — passé pour de bon.",
                              "Not the capture (axb6? only draws — see the trap), not a king move (all six lose: the e-pawn runs). The pawn WALKS PAST b6: black pawns only capture downhill, so a6 is untouchable — passed for good."),
                 "critical": True},
                {"san": "Kb3",
                 "comment": c("La meilleure défense : courir au-devant de la future dame pour esquiver son premier échec.",
                              "The best defence: racing to meet the future queen, hoping to dodge her first check.")},
                {"san": "a7"},
                {"san": "Ka2",
                 "comment": c("En a2, le roi noir croit se cacher… de la colonne a.",
                              "On a2 the black king hopes to hide… on the a-file, of all places.")},
                {"san": "a8=Q+",
                 "comment": c("Raté : la dame naît en donnant l'échec.",
                              "No luck: the queen is born giving check."),
                 "critical": True},
                {"san": "Kb1"},
                {"san": "Qxe4+",
                 "comment": c("Le deuxième point de l'étude : la dame toute neuve rafle le pion e AVEC échec. La contre-promotion est morte avant d'avoir existé.",
                              "The study's second point: the newborn queen scoops the e-pawn WITH check. The counter-promotion is dead before it ever existed."),
                 "critical": True},
                {"san": "Ka1"},
                {"san": "b4",
                 "comment": c("Petit coup de ménage : …b4 est interdit à jamais, b5 et b6 sont figés — spectateurs jusqu'au mat.",
                              "A little housekeeping: …b4 is banned forever, b5 and b6 frozen — spectators until mate.")},
                {"san": "Ka2"},
                {"san": "Qc2+",
                 "comment": c("La boîte se règle : le roi noir n'a plus que a1-b1.",
                              "Setting the box: the black king is down to a1-b1.")},
                {"san": "Ka1"},
                {"san": "Qe2",
                 "comment": c("La dame garde la boîte à distance ; le reste appartient au roi blanc, qui traverse tranquillement l'échiquier (c'est le schéma du cours « Le mat de la dame »).",
                              "The queen holds the box from afar; the rest belongs to the white king, strolling across the board (the pattern of the “Queen Mate” course).")},
                {"san": "Kb1"},
                {"san": "Kd5"},
                {"san": "Ka1"},
                {"san": "Kd4"},
                {"san": "Kb1"},
                {"san": "Kc3",
                 "comment": c("Arrivé.",
                              "Home."),
                 "critical": True},
                {"san": "Ka1"},
                {"san": "Qb2#",
                 "comment": c("Mat — pendant que b5 et b6, intacts, regardent. Les pions noirs n'auront servi à rien : c'était le verdict caché derrière le premier coup.",
                              "Mate — while b5 and b6 watch, untouched. The black pawns never served at all: that was the verdict hiding behind move one."),
                 "critical": True},
            ],
        },
        {
            "chapter": {"id": "race", "title": c("La course des deux dames", "The two-queen race")},
            "moves": [
                "a6",
                {"san": "e3",
                 "comment": c("L'autre grande défense : chacun sa dame, et que le meilleur gagne.",
                              "The other main defence: a queen each, may the better one win.")},
                {"san": "a7"},
                "e2",
                {"san": "a8=Q"},
                {"san": "e1=Q",
                 "comment": c("Les deux dames naissent au même coup. Nulle ? Non — regardez leurs berceaux :",
                              "Both queens are born on the same move. Draw? No — look at their cradles:")},
                {"san": "Qd5+",
                 "comment": c("Depuis a8, la grande diagonale offre l'échec IMMÉDIAT — le tempo qui décide de tout. (Née en b8 après axb6?, la dame n'a pas cet échec : ses lignes butent sur les pions b — voir le piège.)",
                              "From a8 the long diagonal grants an IMMEDIATE check — the tempo that decides everything. (Born on b8 after axb6?, the queen has no such check: her lines run into the b-pawns — see the trap.)"),
                 "critical": True},
                {"san": "Kb4"},
                {"san": "Qd3",
                 "comment": c("Le coup tranquille au milieu de l'orage : le roi noir est en cage (a4/b4), Dc3+ menace, et face à cela la dame e1 n'a pas UNE ressource — la tablebase donne toutes ses réponses perdantes.",
                              "The quiet move in the storm: the black king is caged (a4/b4), Qc3+ looms, and against it the e1-queen has not ONE resource — the tablebase grades every reply as lost."),
                 "critical": True},
                {"san": "Qa1",
                 "comment": c("L'attente — aussi désespérée que le reste.",
                              "Waiting — as hopeless as everything else.")},
                {"san": "Qc3+"},
                {"san": "Ka4"},
                {"san": "b3+",
                 "comment": c("Le pion b2, muet depuis le début de l'étude, donne l'échec décisif.",
                              "The b2-pawn, silent since the study began, delivers the decisive check."),
                 "critical": True},
                {"san": "Ka3"},
                {"san": "Qxa1+",
                 "comment": c("Et la dame noire meurt à l'âge de cinq coups.",
                              "And the black queen dies at five moves old."),
                 "critical": True},
                {"san": "Kxb3",
                 "comment": c("Dame contre deux pions gelés : gain élémentaire. La course était truquée dès 1.a6 — par la géométrie.",
                              "Queen against two frozen pawns: an elementary win. The race was rigged from 1.a6 onward — by geometry.")},
            ],
        },
        {
            "chapter": {"id": "capture", "title": c("La prise naturelle", "The natural capture")},
            "moves": [
                {"san": "axb6", "role": "trap",
                 "comment": c("Le réflexe d'une vie entière : on prend, et le pion passé est là. Comptez pourtant la course qui suit —",
                              "A lifetime's reflex: capture, and the passed pawn is right there. Yet count the race that follows —"),
                 "critical": True},
                {"san": "e3"},
                {"san": "b7"},
                "e2",
                {"san": "b8=Q"},
                {"san": "e1=Q",
                 "comment": c("Le même compte qu'après 1.a6 : dame contre dame au même coup. Mais celle-ci est née en b8 — et depuis b8, PAS d'échec : la colonne b est bouchée par les pions noirs, la diagonale ne mène nulle part. Sans ce premier tempo, aucune géométrie : nulle de bout en bout. Tout Kubbel tient dans la différence entre a8 et b8.",
                              "The same count as after 1.a6: queen for queen on the same move. But this one was born on b8 — and from b8, NO check: the b-file is plugged by Black's own pawns, the diagonal leads nowhere. Without that first tempo there is no geometry: a draw from end to end. All of Kubbel lives in the gap between a8 and b8.")},
            ],
        },
        {
            "chapter": {"id": "king-move", "title": c("Le roi qui « améliore »", "The king who “improves”")},
            "moves": [
                {"san": "Ke5", "role": "trap",
                 "comment": c("Attaquer e4 et « garder toutes les options » ? L'étude est une affaire de temps, et celui-ci PERD :",
                              "Attacking e4, “keeping every option open”? The study is a matter of tempi, and this one LOSES:"),
                 "critical": True},
                {"san": "bxa5",
                 "comment": c("Le pion a5 — le héros de la solution — disparaît, et l'aile dame noire devient une avalanche.",
                              "The a5-pawn — the solution's hero — vanishes, and Black's queenside becomes an avalanche.")},
                {"san": "Kxe4"},
                {"san": "a4"},
                {"san": "Ke3"},
                {"san": "Kb3"},
                {"san": "Kd2"},
                {"san": "Kxb2",
                 "comment": c("Le roi blanc arrive partout une case trop court : le pion a couronne. Résumé de la position initiale, vérifié à l'oracle : dix coups légaux — sept perdent (les six coups de roi, et même b4), axb6 et b3+ ne font qu'annuler, a6 seul gagne. Un coup juste sur dix : c'est une étude.",
                              "The white king is one square short everywhere: the a-pawn queens. The starting position, oracle-checked, in one line: ten legal moves — seven lose (all six king moves, and even b4), axb6 and b3+ merely draw, a6 alone wins. One correct move in ten: that is what a study is.")},
            ],
        },
    ],
}
