# -*- coding: utf-8 -*-
"""Le cavalier de Troïtski (Alexeï Troïtski, 1906) — un cavalier fait les courses, un roi garde la porte.

Position et coup-clé (1.Cg2 !) sourcés ARVES (« instructive studies »,
Troitzky 1906, gain blanc) ; le déroulé complet est dérivé de la tablebase,
qui confirme l'étude au passage : 1.Cg2 est l'UNIQUE gain, et les deux prises
« évidentes » (1.Cxg4?, 1.gxh4?) ne font que nulle.
"""


def c(fr, en):
    return {"fr": fr, "en": en}


COURSE = {
    "id": "eg-troitsky-1906",
    "name": "Troitsky's Knight Errand (1906)",
    "side": "white",
    "kind": "endgame",
    "family": "practical",
    "level": "advanced",
    "rootFEN": "8/8/7p/8/6pp/4N1Pk/5K2/8 w - - 0 1",
    "summary": c(
        "Troïtski, 1906 : le roi noir est enfermé dans une boîte de trois cases — h1, h2, h3 — par un roi et un pion. Pendant que la porte reste fermée, le cavalier blanc part en tournée, mange les pions un à un… puis se sacrifie pour libérer le sien. Du grand art réglé comme une horloge.",
        "Troitsky, 1906: the black king is shut in a three-square box — h1, h2, h3 — by a king and one pawn. While the door stays locked, the white knight goes on its rounds, eats the pawns one by one… then sacrifices itself to set its own pawn free. High art, wound like clockwork.",
    ),
    "lines": [
        {
            "chapter": {"id": "main", "title": c("La tournée du cavalier", "The knight's rounds")},
            "moves": [
                {"san": "Ng2",
                 "comment": c("L'UNIQUE coup gagnant — et le contraire des deux prises naturelles, qui annulent (voir les pièges). Le point : Rf2 et le pion g3 verrouillent la cage h1-h2-h3 ; le cavalier attaque h4 et a l'éternité devant lui.",
                              "The ONLY winning move — the opposite of the two natural captures, which merely draw (see the traps). The point: Kf2 and the g3-pawn lock the h1-h2-h3 cage; the knight attacks h4 with all eternity ahead of it."),
                 "critical": True},
                {"san": "Kh2",
                 "comment": c("Le roi noir n'a que la navette. Notez que …g4-g3 n'existe pas : le pion blanc occupe la case.",
                              "The black king can only shuttle. Note that …g4-g3 does not exist: the white pawn owns that square.")},
                {"san": "Nxh4",
                 "comment": c("Première course : le pion h4.",
                              "First errand: the h4-pawn.")},
                {"san": "Kh1"},
                {"san": "Nf5",
                 "comment": c("Le cavalier repart par f5 — vers h6. La cage, elle, ne bouge pas d'un pouce.",
                              "The knight sets off again via f5 — bound for h6. The cage, meanwhile, does not budge an inch.")},
                {"san": "Kh2"},
                {"san": "Nxh6",
                 "comment": c("Deuxième course. Il ne reste au camp noir que le pion g4 — précisément celui qui bloque le pion blanc.",
                              "Second errand. Black is down to the g4-pawn — precisely the one blockading White's own.")},
                {"san": "Kh3"},
                {"san": "Nf5"},
                {"san": "Kh2"},
                {"san": "Nd4",
                 "comment": c("Le détour se resserre : d4 prépare l'entrée en f3.",
                              "The loop tightens: d4 prepares the hop into f3.")},
                {"san": "Kh1"},
                {"san": "Nf3",
                 "comment": c("La pointe de l'étude : le cavalier s'offre au pion g4. Prendre libère g3 ; refuser laisse le cavalier et le roi cueillir g4 au coup suivant — la tablebase ne donne aux Noirs rien de mieux que d'accepter.",
                              "The study's point: the knight offers itself to the g4-pawn. Taking frees g3; declining lets knight and king pick up g4 next move — the tablebase gives Black nothing better than to accept."),
                 "critical": True},
                {"san": "gxf3"},
                {"san": "Kxf3",
                 "comment": c("Bilan de la tournée : les trois pions noirs ont disparu, le pion g3 est passé, et le roi noir n'a jamais quitté sa boîte.",
                              "The rounds are done: all three black pawns gone, the g3-pawn passed, and the black king never left its box."),
                 "critical": True},
                {"san": "Kh2"},
                {"san": "g4"},
                {"san": "Kh3",
                 "comment": c("Le roi noir sort enfin — pour courir après un train déjà parti.",
                              "The black king finally gets out — to chase a train that has already left.")},
                {"san": "g5"},
                "Kh4",
                {"san": "g6"},
                {"san": "Kg5"},
                {"san": "g7",
                 "comment": c("g8=D suit. Depuis le premier coup, toute l'étude tenait en une phrase : la cage ne coûtait que DEUX gardiens, le cavalier était donc libre — y compris de mourir au bon moment.",
                              "g8=Q next. From move one the whole study fitted in a sentence: the cage cost only TWO warders, so the knight was free — free even to die at the right moment."),
                 "critical": True},
            ],
        },
        {
            "chapter": {"id": "h5-push", "title": c("Si les Noirs poussent h5", "If Black pushes h5")},
            "moves": [
                "Ng2",
                {"san": "h5",
                 "comment": c("L'autre défense sérieuse : soustraire le pion h6 à la tournée. Mais la roue du cavalier a plus d'un rayon :",
                              "The other serious defence: pulling the h6-pawn out of the knight's rounds. But the knight's wheel has more than one spoke:")},
                {"san": "Nxh4",
                 "comment": c("Prise — et le manège recommence, une case plus loin.",
                              "Captured — and the carousel restarts, one square along.")},
                {"san": "Kh2"},
                {"san": "Ng2",
                 "comment": c("Retour par la case de départ : le circuit g2-f4 vise h5 comme il visait h4.",
                              "Back through the starting square: the g2-f4 circuit aims at h5 exactly as it aimed at h4.")},
                {"san": "Kh1"},
                {"san": "Nf4"},
                {"san": "Kh2"},
                {"san": "Nxh5",
                 "comment": c("Deuxième pion. Le troisième attend toujours en g4, cloué sur place.",
                              "Second pawn. The third still waits on g4, nailed to the spot.")},
                {"san": "Kh1"},
                {"san": "Nf6"},
                {"san": "Kh2"},
                {"san": "Nxg4+",
                 "comment": c("Troisième pion — avec échec, cette fois : nul besoin de se sacrifier, la version h5 s'effondre plus vite encore.",
                              "Third pawn — with check this time: no sacrifice needed, the h5 version collapses even faster."),
                 "critical": True},
                {"san": "Kh1"},
                {"san": "Ne3",
                 "comment": c("Cavalier et pion contre roi nu : g4-g5-g6… La morale est la même dans toutes les branches : les pions noirs n'étaient pas une force, mais un garde-manger.",
                              "Knight and pawn against a bare king: g4-g5-g6… The moral is the same in every branch: the black pawns were never a force, only a pantry.")},
            ],
        },
        {
            "chapter": {"id": "greedy-knight", "title": c("La prise gourmande", "The greedy capture")},
            "moves": [
                {"san": "Nxg4", "role": "trap",
                 "comment": c("Prendre le pion central, défendu par personne — le réflexe. Mais ce pion-là était EN PRISE pour une raison :",
                              "Grabbing the central pawn, defended by nobody — pure reflex. But that pawn hung for a reason:"),
                 "critical": True},
                {"san": "Kxg4",
                 "comment": c("…le roi noir le reprend et sort de la cage par la même porte.",
                              "…the black king takes it back and walks out of the cage through the same door.")},
                {"san": "gxh4"},
                {"san": "Kxh4",
                 "comment": c("Bilan : plus un pion blanc sur l'échiquier, un pion noir encore en h6 — c'est BLANC qui doit faire la nulle (le roi touche le coin : pion tour, forteresse connue). De gagnant à défenseur en deux coups.",
                              "The tally: not one white pawn left, a black pawn still on h6 — WHITE is the one who must hold the draw (his king reaches the corner: rook pawn, the known fortress). From winner to defender in two moves.")},
            ],
        },
        {
            "chapter": {"id": "greedy-pawn", "title": c("L'autre prise", "The other capture")},
            "moves": [
                {"san": "gxh4", "role": "trap",
                 "comment": c("Même famille d'erreur, autre exécutant : le pion abandonne g3 — la serrure de la cage.",
                              "Same family of error, different culprit: the pawn abandons g3 — the lock of the cage."),
                 "critical": True},
                {"san": "Kxh4"},
                {"san": "Nxg4",
                 "comment": c("Le cavalier ramasse g4 au passage, mais :",
                              "The knight scoops up g4 in passing, but:")},
                {"san": "Kxg4",
                 "comment": c("…tout s'évapore : roi contre roi et pion h — le roi blanc court en h1, nulle. Les deux prises mènent à la même impasse ; seule la cage fermée de 1.Cg2 ! gardait le butin entier.",
                              "…everything evaporates: king against king and h-pawn — the white king runs to h1, draw. Both captures reach the same dead end; only the locked cage of 1.Ng2! kept the loot intact.")},
            ],
        },
    ],
}
